version: '3.9'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khuong123
      POSTGRES_DB: collector-data-service
    networks:
      - app-net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d collector-data-service" ]
      interval: 10s
      retries: 5
      start_period: 20s

  # ===== CONFIG SERVER =====
  config-server:
    build: ./config-server
    container_name: config-server-2
    ports:
      - "8888:8888"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  # --- Eureka Discovery Server ---
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server-2
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s


  # --- API Gateway ---
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-2
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  collector-data-service:
    build: ./collector-data-service
    container_name: collector-data-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
      postgresql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: collector-data-service
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    networks:
      - app-net

  search-service:
    build: ./search-service
    container_name: search-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
      postgresql:
        condition: service_healthy
      collector-data-service:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: search-service
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    networks:
      - app-net

  citizen-report-service:
    build: ./citizen-report-service
    container_name: citizen-report-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_started
      postgresql:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: citizen-report-service
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
